train:
  data: datasets/construction-ppe.yaml
  model: yolov8n.pt
  epochs: 1
  imgsz: 512
  batch: 4
  device: cpu
  conf: 0.25

paths:
  artifacts_dir: artifacts
  outputs_dir: outputs
  reports_dir: reports

mlflow:
  tracking_uri: http://127.0.0.1:5000
  experiment: ppe-detection
